.env, .env.production, .env.test, package.json, src/views/Entrepreneur.vue
Pull request for issue https://github.com/I-OWE-YOU/web-frontend/issues/26
=> Create env settings to differentiate between test and production API

src/design/_mixins.scss
=> Responsiveness of button in the home screen

src/views/Entrepreneur.vue
Related to https://github.com/I-OWE-YOU/web-frontend/issues/30
=> fixed back button issues

src/App.vue, src/components/ButtonLink.vue, src/components/FormField.vue, src/design/_mixins.scss, src/design/_sizes.scss
- moved absolute values to _sizes.scss
- removed unnecessary CSS classes
- added responsiveness to form input fields to match form buttons
- removed styles duplication
=> small styles clean up

src/components/FormField.vue
=> Added id to input to connect it with label

src/components/entrepreneur-flow/EntrepreneurFlowIntro.vue, src/components/entrepreneur-flow/EntrepreneurFlowStepTemplate.vue, src/views/Entrepreneur.vue
- created template component for flow steps
- created ccomponent for the intro step
plan for the next steps - extract components markup and logic (validation, button click handlers, web requests, etc.) into a separate files
=> Start of extracting Entrepreneur.vue steps into separate files

src/components/FormField.vue, src/views/Entrepreneur.vue
=> added inputmode for the FormField component

src/design/_colors.scss, src/design/_mixins.scss, src/design/_sizes.scss, src/views/Entrepreneur.vue
=> Border for focused button and background color for the hovered input

src/router/index.js, src/router/routes.js, src/views/TermsAndConditions.vue
- add route for terms and conditions,
- create component for terms and conditions
- add some basic styling for terms and conditions page
=> Create terms and conditions page

.env, package.json, src/design/_sizes.scss, src/router/routes.js, src/views/Home.vue, src/views/LetMeHelp.vue, yarn.lock
All the vuejs google maps libraries I found are not maintained properly. Using google JS API directly
Closes #80
=> Google map without default controls, with focus on the current user location

src/design/_sizes.scss, src/views/LetMeHelp.vue
=> Added field to navigate to the location

.env, src/App.vue, src/router/index.js, src/router/routes.js, src/test-data/companies.js, src/typings/company.js, src/views/Coupons.vue, src/views/Entrepreneur.vue, src/views/LetMeHelp.vue
- show all companies on the map
- show company details after the marker is clicked
- navigate to the dummy coupons page 
Closes #77
=> Companies on the map

src/router/index.js, src/router/routes.js, src/views/SignIn.vue
=> create signIn component

src/App.vue, src/design/_colors.scss, src/design/_fonts.scss, src/router/index.js, src/router/routes.js, src/views/CouponConfirm.vue, src/views/Coupons.vue
=> Select coupon pages

src/main.js, src/router/index.js, src/router/routes.js, src/views/StripeConnect.vue
This is not the final product. But it will help us to demonstrate the flow for connecting with Stripe Connect
=> stripe connect page

src/test-data/companies.js, src/typings/company.js, src/views/LetMeHelp.vue
- Use companyId instead of id for the company
- Validation of langitude and longtitude
=> fix the placing of companies on the map

src/views/Coupons.vue
=> Validation logic and message for coupon amount

src/App.vue, src/components/ButtonLink.vue, src/components/Nav.vue, src/components/entrepreneur-flow/EntrepreneurFlowBusinessInfo.vue, src/components/entrepreneur-flow/EntrepreneurFlowFinish.vue, src/components/entrepreneur-flow/EntrepreneurFlowIntro.vue, src/components/entrepreneur-flow/EntrepreneurFlowPersonName.vue, src/components/entrepreneur-flow/EntrepreneurFlowSetupPayment.vue, src/design/_button.scss, src/design/_mixins.scss, src/views/Header.vue, src/views/Home.vue, src/views/SignIn.vue, src/views/SignUp.vue
- add header
- add hamburger menu
- remove mixin for buttons, add big red button instead
=> add header and hamburger menu

src/components/Nav.vue, src/components/SignOut.vue, src/main.js, src/router/index.js, src/views/SignIn.vue, src/views/constants.js
[ close #102 ]
- add event listener 'signedOut' and redirect to home
- collapse nav onclick
- change items name in nav
- set conditional rendering based on auth state in nav
- emit value when user signedOut
- change animation of nav open/close button
=> render sign in/sign out in header based on auth state

src/components/Nav.vue, src/router/index.js, src/router/routes.js, src/views/PrivacyStatement.vue
=> - create privacy statement page

src/components/entrepreneur-flow/EntrepreneurFlowBusinessInfo.vue, src/design/_button.scss, src/design/_sizes.scss, src/views/Entrepreneur.vue, src/views/Header.vue, src/views/SignUp.vue, src/views/constants.js
[close #104]
- remove unnecessary fields from business Owner registration flow
- add address check-in business owner flow
- add fields to confirm password and email on sign up page
- small adjustments on styles
=> Align flow with design

src/views/CouponConfirm.vue
=> Added the second email field to coupon order page

src/views/Home.vue, yarn.lock
=> Play video from home page at full screen

src/components/Nav.vue
=> add transparent dots to bottom of nav

src/views/CouponConfirm.vue, src/views/Coupons.vue, src/views/CustomerLandingPage.vue, src/views/EntrepreneurFlowFinish.vue, src/views/SignIn.vue, src/views/SignUp.vue
=> Translations and texts updates

src/router/index.js, src/views/SignUp.vue
=> add nav guard to protect /Entrepreneur from not Auth users

src/views/SignUp.vue
=> increase password length requirement

src/components/entrepreneur-flow/EntrepreneurFlowBusinessInfo.vue
=> Dutch translation
